Repository netr0m/az-pim-cli, pull requests merged in 2024-06, with the labels that each got.

#16 feat: support for PIM Entra groups
  README.md
  cmd/activate.go
  cmd/list.go
  cmd/root.go
  pkg/pim/client.go
  pkg/pim/const.go
  pkg/pim/models.go
  pkg/pim/utils.go
  pkg/utils/main.go
Labels: documentation, enhancement

#18 chore: ensure consistent flag names
  README.md
  cmd/activate.go
  cmd/list.go
  cmd/root.go
  go.mod
  go.sum
  pkg/utils/main.go
Labels: documentation, enhancement

#12 fix: use exact matching for the role selection
  pkg/utils/main.go
Labels: bug

#22 feat: dry-run for 'activate'
  README.md
  cmd/activate.go
Labels: documentation, enhancement

#28 chore: update dependencies
  go.mod
  go.sum
Labels: dependencies, security

#29 ci: added semgrep workflow
  .github/workflows/on-pull-request.yaml
  .github/workflows/on-schedule.yaml
  .github/workflows/semgrep.yaml
Labels: cicd

#30 feat: add 'version' command
  cmd/version.go
Labels: enhancement

#33 ci(fix): set permissions for scheduled workflow
  .github/workflows/on-schedule.yaml
Labels: bug, cicd

#35 chore(main): release az-pim-cli 1.0.0
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending
